"""Model registry — pluggable model architectures for Agent-driven design.

New models generated by ModelAgent are registered here. Training and
inference look up models by name. Any model in registry/ follows this
contract:

    class MyModel(nn.Module):
        def __init__(self, config: ModelConfig):
            ...
        def forward(self, batch: dict) -> tuple:
            '''batch keys: mol_tokens, mol_distances, mol_edge_types,
                          pocket_tokens, pocket_distances, pocket_edge_types
               returns: (mol_emb, pocket_emb) — both (B, project_dim), L2-norm
            '''
            return mol_emb, pocket_emb
"""

import importlib
import sys
from pathlib import Path
from typing import Dict, Optional

import torch.nn as nn

# Built-in models
_DEFAULT_MODEL = "drugclip"

# Registry: name → (module_path, class_name)
_REGISTRY: Dict[str, dict] = {
    "drugclip": {
        "module": "train.model.drugclip",
        "class": "DrugCLIP",
        "source": "built-in",
        "description": "Dual UniMol Transformer with GBF distance encoding",
    },
}


def register(name: str, module_path: str, class_name: str,
             source: str = "agent", description: str = ""):
    """Register a model architecture.

    Args:
        name: short name for config/training reference
        module_path: Python import path, e.g. 'train.model.drugclip'
        class_name: class name within the module
        source: where it came from (built-in, agent, user)
        description: one-line description
    """
    _REGISTRY[name] = {
        "module": module_path,
        "class": class_name,
        "source": source,
        "description": description,
    }


def get_model(name: str = None, config=None) -> nn.Module:
    """Instantiate a model by name. Falls back to DrugCLIP if name not found.

    Args:
        name: model name in registry (default: drugclip)
        config: ModelConfig instance

    Returns:
        nn.Module instance
    """
    name = name or _DEFAULT_MODEL
    entry = _REGISTRY.get(name)
    if entry is None:
        # Fallback to DrugCLIP
        entry = _REGISTRY[_DEFAULT_MODEL]

    module = importlib.import_module(entry["module"])
    cls = getattr(module, entry["class"])
    return cls(config)


def list_models() -> dict:
    """Return registry summary for LLM consumption."""
    return {
        name: {"class": e["class"], "source": e["source"], "desc": e["description"]}
        for name, e in _REGISTRY.items()
    }


def scan_agent_models(model_dir: str = None):
    """Scan train/model/ for agent-generated model files and auto-register them.

    Agent-generated files follow the naming convention: model_<name>.py
    Each must contain a class named 'Model' (convention).
    """
    if model_dir is None:
        model_dir = Path(__file__).parent
    else:
        model_dir = Path(model_dir)

    for py_file in sorted(model_dir.glob("model_*.py")):
        name = py_file.stem.replace("model_", "")
        if name in _REGISTRY:
            continue  # already registered

        module_path = f"train.model.{py_file.stem}"
        # Try to import and check for 'Model' class
        try:
            mod = importlib.import_module(module_path)
            if hasattr(mod, "Model"):
                register(
                    name=name,
                    module_path=module_path,
                    class_name="Model",
                    source="agent",
                    description=getattr(mod, "DESCRIPTION", f"Agent-generated: {name}"),
                )
        except Exception:
            pass


def get_registry() -> Dict:
    return dict(_REGISTRY)
